-- Sequence
CREATE SEQUENCE PROJECT.INSTALLMENTS_PAID_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
-- Trigger
CREATE TRIGGER PROJECT.INSTALLMENTS_PAID_TRG
BEFORE INSERT
ON PROJECT.INSTALLMENTS_PAID
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column INSTALLMENT_ID
  :new.INSTALLMENT_ID := INSTALLMENTS_PAID_SEQ.nextval;
END INSTALLMENTS_PAID_TRG;
/
