CREATE OR REPLACE TRIGGER PROJECT.UPD_INSTALLMENT_DATA
AFTER INSERT
ON PROJECT.CONTRACTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN

            PROJECT.SET_INSTALLMENTS_NO ( :NEW.CONTRACT_ID );

            PROJECT.SET_INSTALLMENTS ( :NEW.CONTRACT_ID  );
            
END;



