CREATE OR REPLACE PROCEDURE PROJECT.SET_INSTALLMENTS ( P_CONTRACT_ID  number)
IS
 CONTRACTS_REC CONTRACTS%ROWTYPE  ;
 
V_INSTALLMENTS NUMBER(8);
V_MONTH DATE;
V_INSTALL_AMOUNT NUMBER (8 , 2);
 
BEGIN
                SELECT * INTO CONTRACTS_REC
                FROM PROJECT.CONTRACTS
                WHERE CONTRACT_ID = P_CONTRACT_ID;

                       V_MONTH := CONTRACTS_REC.CONTRACT_STARTDATE;
                       V_INSTALL_AMOUNT := (CONTRACTS_REC.CONTRACT_TOTAL_FEES - NVL(CONTRACTS_REC.CONTRACT_DEPOSIT_FEES,0)) / CONTRACTS_REC.PAYMENT_INSTALLMENTS_NO ;
                      V_INSTALLMENTS :=  MONTHS_BETWEEN(CONTRACTS_REC.CONTRACT_ENDDATE , CONTRACTS_REC.CONTRACT_STARTDATE )  / CONTRACTS_REC.PAYMENT_INSTALLMENTS_NO ;


                    FOR I IN 1..CONTRACTS_REC.PAYMENT_INSTALLMENTS_NO LOOP
    
                    --CONTRACT_ID, CONTRACT_STARTDATE, CONTRACT_ENDDATE, PAYMENT_INSTALLMENTS_NO, CONTRACT_TOTAL_FEES, CONTRACT_DEPOSIT_FEES, CLIENT_ID, CONTRACT_PAYMENT_TYPE
                        
                    INSERT INTO PROJECT.INSTALLMENTS_PAID ( CONTRACT_ID, INSTALLMET_DATE, INSTALLEMENT_AMT, PAID)
                    VALUES (CONTRACTS_REC.CONTRACT_ID , V_MONTH , V_INSTALL_AMOUNT ,  0);

                    V_MONTH := add_months(V_MONTH , V_INSTALLMENTS);
                        
                    END LOOP;
                    
END;
